# Guia da config:
#
# defaultStatus - é o status padrão do grace. (quando o plugin inicia ele verifica por aqui se ele está ou não ativo)
# timeToEnd - é o tempo em que o grace acabará. (o tempo é em ticks, usa esse site para converter ticks em tempo real: https://www.mapmaking.fr/tick/)
settings:
  defaultStatus: false
  timeToEnd: 6000

messages:
  not-in-grace: '&cO grace já acabou ou não foi iniciado.'
  in-grace: '&aAtualmente o modo grace está ativado.'
  enabled-grace:
    - ''
    - '&a&l GRACE!'
    - '&f O grace foi ativado!'
    - '&f durante o grace, pvp e'
    - '&f explosões estão desativados.'
    - ''
  disabled-grace:
    - ''
    - '&c&l GRACE!'
    - '&f O grace foi desativado!'
    - '&f explosões e pvp agora estão liberados.'
    - ''